[package]
name = "snapmail_cli"
version = "0.0.1"
keywords = [ "holochain" ]
categories = [ "command-line-utilities"]
edition = "2018"

[[bin]]
name = "snapmail-cli"
path = "src/main.rs"

[[bin]]
name = "rustify-wasm"
path = "src/rustify-wasm.rs"

[[bin]]
name = "snapmail-tui"
path = "src/main-tui.rs"

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true # link time optimization

[profile.dev.package."*"]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16

[patch.crates-io]
rkv = { git = "https://github.com/holochain/rkv.git", branch = "master" }
lmdb-rkv = { git = "https://github.com/holochain/lmdb-rs.git" }

[dependencies]
strum = "0.19"
strum_macros = "0.19"
crossterm = { version = "0.19", features = [ "serde" ] }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
#rand = { version = "0.7.3", default-features = false, features = ["std"] }
tui = { version = "0.15", default-features = false, features = ['crossterm', 'serde'] }
directories = "3.0.1"
anyhow = "1.0"
ansi_term = "0.12"
futures = "0.3"
lazy_static = "1.4.0"
thiserror = "1.0.24"
observability = "0.1.3"
serde_yaml = "0.8"
structopt = "0.3"
url2 = "0.0.6"
regex = "1"
base64 = "0.13"
tokio = { version = "1.5", features = [ "full" ] }
tokio-stream = { version = "0.1.5" }
futures-util = "0.3.1"
snapmail = { path = "../snapmail-rsm/zomes/snapmail" }
holochain_serialized_bytes = "=0.0.50"
tokio_helper = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "tokio_helper" }
holo_hash = { version = "^0.0.2-alpha.1", path = "../holochain/crates/holo_hash", features = ["string-encoding"] }
holochain_keystore = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holochain_keystore" }
holochain = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holochain", features = ["test_utils"] }
holochain_zome_types = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holochain_zome_types" }
holochain_cli_bundle = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holochain_cli_bundle" }
holochain_conductor_api = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holochain_conductor_api" }
holochain_types = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holochain_types" }
holochain_websocket = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holochain_websocket" }
holochain_p2p = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holochain_p2p" }


[dev-dependencies]
assert_cmd = "1.0.1"
matches = "0.1"
portpicker = "0.1.0"

