[package]
name = "snapmail_cli"
version = "0.0.1"
keywords = [ "holochain" ]
categories = [ "command-line-utilities"]
edition = "2018"

[[bin]]
name = "snapmail-cli"
path = "src/main.rs"

[profile.dev.package."*"]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16

[patch.crates-io]

rkv = { git = "https://github.com/holochain/rkv.git", branch = "master" }
lmdb-rkv = { git = "https://github.com/holochain/lmdb-rs.git" }

[dependencies]
anyhow = "1.0"
ansi_term = "0.12"
chrono = "0.4.6"
futures = "0.3"
lazy_static = "1.4.0"
derive_more = "0.99"
holochain_cli_bundle = { path = "../holochain/crates/hc_bundle" }
holochain_conductor_api = { path = "../holochain/crates/holochain_conductor_api" }
holochain_types = { path = "../holochain/crates/holochain_types" }
holochain_websocket = { path = "../holochain/crates/holochain_websocket" }
holochain_p2p = { path = "../holochain/crates/holochain_p2p" }
nanoid = "0.3"
observability = "0.1.3"
serde_yaml = "0.8"
tokio = { version = "1.3", features = [ "full" ] }
structopt = "0.3"
tracing = "0.1"
url2 = "0.0.6"
walkdir = "2"

[dev-dependencies]
assert_cmd = "1.0.1"
matches = "0.1"
portpicker = "0.1.0"

