[package]
name = "rustify_wasm"
version = "0.0.1"
keywords = [ "holochain" ]
categories = [ "command-line-utilities"]
edition = "2018"

[[bin]]
name = "rustify-wasm"
path = "src/main.rs"

[dependencies]
yazi = "0.1.3"
anyhow = "1.0"
base64 = "0.13"
tokio = { version = "1.5", features = [ "full" ] }
# 385 deps wtf
holochain_types = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holochain_types" }


