[package]
name = "snapmail_common"
version = "0.0.1"
keywords = [ "holochain" ]
categories = [ "command-line-utilities"]
edition = "2018"

[dependencies]
yazi = "0.1.3"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
directories = "3.0.1"
anyhow = "1.0"
ansi_term = "0.12"
lazy_static = "1.4.0"
thiserror = "1.0.24"
serde_yaml = "0.8"
url2 = "0.0.6"
base64 = "0.13"
snapmail = { path = "../../../snapmail-rsm/zomes/snapmail" }

tokio_helper = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "tokio_helper" }
holo_hash = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holo_hash", features = ["string-encoding"] }
holochain_keystore = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holochain_keystore" }
holochain = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holochain", features = ["test_utils"] }
holochain_zome_types = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holochain_zome_types" }
holochain_conductor_api = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holochain_conductor_api" }
holochain_types = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holochain_types" }
holochain_p2p = { git = "https://github.com/holochain/holochain.git", rev = "7f7c926d8eaf57f007848880eea56bf296410096", package = "holochain_p2p" }
